[package]
name = "twitbeam"
version = "0.1.0"
authors = ["Yoshiori SHOJI <yoshiori@gmail.com>"]

[dependencies]
hyper = "0.10.10"
hyper-native-tls = "0.2.2"
serde_json = "1.0.2"
regex = "0.2.2"
rustyline = "1.0.0"
